### ISSUE TITLE
FEAT: 시음노트 상세페이지 구현

### ISSUE THREAD

**Issue by yeki6110** [juulabel/juulabel-front#21]
### 어떤 기능인가요?

작성된 시음노트를 볼 수 있는 화면

### 작업 상세 내용

1.  유저 프로필 사진 및 유저 닉네임, 작성 일시, 전통주 이미지
2.  제품명, 술 정보(주종, 도수, 양조장) 
3.  술평가 - container: 술색, text: 탁도, 점성도
4. 술 맛 그래프
5. 부연 설명
6. 달점 (사진 + 슬라이더) - 슬라이더를 숨겨두고 z index 해서 그위에 달점을 나타낸다
8. 좋아요, 댓글 창

**Comment by kimjaewoo2233** [comment]
댓글 아이콘 수정, 레이더 차트 수정, 좋아요 백그라운드 색깔 다른거 수정, 박스 그림자 추가하고 머지 시켰습니다.
술 정보보러 가기는 전통주 상세 페이지 작업할때 추가해서 pr 날리겠습니다!
